import Head from 'next/head'

import { gqlShopify } from '@/pages/api/graphql'
import { GET_PAYMENT_METHODS, GET_SHOP_NAME } from '@/pages/api/queries'

const AboutUs = ({ shopName }: any) => {
	return (
		<>
			<Head>
				<title>{shopName}</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			asd
		</>
	)
}

export const getServerSideProps = async () => {
	const shop = await gqlShopify(GET_SHOP_NAME, {})

	const paymentMethods = await gqlShopify(GET_PAYMENT_METHODS, {})

	const gqlData = {
		shopName: shop.shop.name,
		paymentMethods: paymentMethods.shop.paymentSettings,
	}

	return {
		props: { ...gqlData },
	}
}

export default AboutUs
