import Head from 'next/head'

import { gqlShopify } from '@/pages/api/graphql'
import {
	GET_PAYMENT_METHODS,
	GET_RECIPE,
	GET_SHOP_NAME,
} from '@/pages/api/queries'

import PageHeader from '@/components/PageHeader'
import { parseHtml } from '@/utils/utils'

const RecipePage = ({ shopName, recipe }: any) => {
	const title = `${shopName} | Recept - ${recipe.title}`
	const ingredients = parseHtml(JSON.parse(recipe.ingredients?.value))

	console.log(recipe)
	console.log(ingredients)

	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<PageHeader>{recipe.title}</PageHeader>
		</>
	)
}

export const getServerSideProps = async (context: any) => {
	const { recept } = context.query

	const recipe = await gqlShopify(GET_RECIPE, { handle: recept })

	const shop = await gqlShopify(GET_SHOP_NAME, {})

	const paymentMethods = await gqlShopify(GET_PAYMENT_METHODS, {})

	const gqlData = {
		shopName: shop.shop.name,
		recipe: recipe.blog.articleByHandle,
		paymentMethods: paymentMethods.shop.paymentSettings,
	}

	return {
		props: { ...gqlData },
	}
}

export default RecipePage
