import Head from 'next/head'

import { getAllGqlShopify, gqlShopify } from '@/pages/api/graphql'
import {
	GET_PAYMENT_METHODS,
	GET_RECIPES,
	GET_SHOP_NAME,
} from '@/pages/api/queries'

import layout from '@/styles/Layout.module.scss'
import PageHeader from '@/components/PageHeader'
import Recipe from '@/components/Recipe'

const Recipes = ({ shopName, allRecipies }: any) => {
	const title = `${shopName} | Recept`

	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<PageHeader>Recept</PageHeader>
			<div className={layout.container}>
				<div className={layout.grid_container}>
					{allRecipies.map((recipe: any) => (
						<Recipe key={recipe.node.handle} recipe={recipe} />
					))}
				</div>
			</div>
		</>
	)
}

export const getServerSideProps = async () => {
	const shop = await gqlShopify(GET_SHOP_NAME, {})

	const allRecipies = await getAllGqlShopify('articles', GET_RECIPES, {
		amount: 20,
	})

	const paymentMethods = await gqlShopify(GET_PAYMENT_METHODS, {})

	const gqlData = {
		shopName: shop.shop.name,
		allRecipies: allRecipies,
		paymentMethods: paymentMethods.shop.paymentSettings,
	}

	return {
		props: { ...gqlData },
	}
}

export default Recipes
