export { default as FiskPlate } from './FiskPlate'
export { default as SkaldjurPlate } from './SkaldjurPlate'
export { default as PaketPlate } from './PaketPlate'
export { default as RomPlate } from './RomPlate'
export { default as KaviarPlate } from './KaviarPlate'
