import Head from 'next/head'

import { gqlShopify } from './api/graphql'
import { GET_PAGE_CONTENT, GET_SHOP_NAME } from './api/queries'

import styles from '@/styles/Home.module.scss'
import Hero from '@/components/Hero'
import { generateImageSrcFromString } from '@/utils/utils'

const Home = ({ shopName, heroContent, heroImage }: any) => {
	return (
		<>
			<Head>
				<title>{shopName}</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Hero heroContent={heroContent} heroImage={heroImage} />
			<main className={styles.main}>
				<h2>{heroContent.title}</h2>
				<p dangerouslySetInnerHTML={{ __html: heroContent.body }}></p>
			</main>
		</>
	)
}

export const getServerSideProps = async () => {
	const shop = await gqlShopify(GET_SHOP_NAME, {})

	const hero = await gqlShopify(GET_PAGE_CONTENT, {
		handle: 'hero',
	})

	const heroImage = await gqlShopify(GET_PAGE_CONTENT, {
		handle: 'hero-image',
	})

	const gqlData = {
		shopName: shop.shop.name,
		heroContent: hero.page,
		heroImage: generateImageSrcFromString(heroImage.page.body),
	}

	return {
		props: { ...gqlData },
	}
}

export default Home
