import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'

import { gqlShopify } from './api/graphql'
import { GET_PAGE_CONTENT, GET_SHOP_NAME } from './api/queries'

const Home = ({ gqlData }: any) => {
	const { heroContent, shopName } = gqlData

	return (
		<>
			<Head>
				<title>{shopName}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main className={styles.main}>
				<Image src='/LOGO_skylt.png' alt='logo' width={20} height={20} />
				<h2>{heroContent.title}</h2>
				<p dangerouslySetInnerHTML={{ __html: heroContent.body }}></p>
			</main>
		</>
	)
}

export const getServerSideProps = async () => {
	const hero = await gqlShopify(GET_PAGE_CONTENT, {
		handle: 'hero',
	})

	const shop = await gqlShopify(GET_SHOP_NAME, {
		handle: 'hero',
	})

	const gqlData = { heroContent: hero.page, shopName: shop.shop.name }
	console.log(gqlData)

	return {
		props: { gqlData },
	}
}

export default Home
